### ISSUE TITLE
Cant render component in MDX

### ISSUE THREAD

**Issue by ted123** [nihgwu/storybook-addon-react-runner#1]
Hi @nihgwu , I tried adding storybook-addon-react-runner in my storybook addon, but after I added it my MDX is no longer showing the component. Do you know what might have cause this issue?

**Comment by nihgwu** [comment]
How do you use it? It works fine for me https://github.com/nihgwu/storybook-addon-react-runner/blob/main/stories/Button.stories.mdx https://nihgwu.github.io/storybook-addon-react-runner/?path=/story/example-mdx--primary

**Comment by ted123** [comment]
Here is my mdx file: https://raw.githubusercontent.com/ted123/lerna-storybook/react-runner/packages/Button/stories/Button.stories.mdx link to repo for full reference: https://github.com/ted123/lerna-storybook/tree/react-runner  . Im not sure if my storybook configuration is correct but running storybook without the storybook-addon-react-runner add on works fine, but when I add it my component wont show up. Im wondering if its because Im using webpack 5 or due to a faulty configuraion

**Comment by nihgwu** [comment]
@ted123 I found the issue, I made it to support Args by checking `(args) =>` but for MDX Story the generated code is using `args =>`, I'll release a fix soon

**Comment by nihgwu** [comment]
please try 0.2.3

**Comment by ted123** [comment]
Hi @nihgwu, I tried 0.2.3 and now I am seeing this error:
<img width="1065" alt="Screen Shot 2022-03-16 at 10 15 40 AM" src="https://user-images.githubusercontent.com/5461270/158503296-fe05babd-acbb-4a69-a2af-7b6686afdaed.png">

**Comment by nihgwu** [comment]
@ted123 ~~what's the code? Could you expand it?~~ never mind, the problem is that in your code you export `Button` as default, so [in this line](https://github.com/ted123/lerna-storybook/blob/react-runner/.storybook/preview.js#L1) you should use `import Button from "../packages/Button/src";`

**Comment by ted123** [comment]
Thanks for taking a look at it @nihgwu ! I needed to add curly brace to my imported Button like this ```import { Button } from "../src"``` and it worked. However the react-runner is not showing up, I checked console and I got this: <img width="1242" alt="Screen Shot 2022-03-17 at 8 26 59 AM" src="https://user-images.githubusercontent.com/5461270/158713241-3526a131-1e0c-4550-8fe5-14897dc19be8.png">

**Comment by nihgwu** [comment]
@ted123 thanks for reporting, I'm working on a fix

**Comment by nihgwu** [comment]
webpack5 support is added in v0.3.0, btw you don't need to add [this block](https://github.com/ted123/lerna-storybook/blob/react-runner/.storybook/webpack.config.js#L10-L15) as it's already included in this addon
