### ISSUE TITLE
Breaking HMR reload

### ISSUE THREAD

**Issue by jesscleeCH** [nihgwu/storybook-addon-react-runner#3]
Hi @nihgwu, this addon seems to be breaking my webpack's HMR. The live code edit works fine locally, but when I change my .tsx files, I get the below errors and the changes aren't reflected in storybook:
![Screen Shot 2022-04-11 at 1 22 02 PM](https://user-images.githubusercontent.com/89034194/162807955-eb2b8df9-ad29-4630-85df-6741450af953.png)
I'm still able to change .mdx files, though. I'm using webpack version 4.46.0 and Storybook version 6.4.19.
Also, when I disable the live code edit, I continue to get the same errors but the changes **are** reflected in storybook, so the problems seems semi-fixed. When I completely uninstall this addon, HMR works fine with reloading.
![Screen Shot 2022-04-11 at 1 49 31 PM](https://user-images.githubusercontent.com/89034194/162808860-b324a523-ccdd-4688-b01e-ef871434e06e.png)
Do you have an idea on why this would be happening?

**Comment by nihgwu** [comment]
I think it's expected as scope is statically configured, I don't think it would work with HMR, probably it would work if set scope from stories level instead of project level

**Comment by nihgwu** [comment]
OK I just did some experiments, yes if you move scope configuration from `preview.js`(and ofc you should remove the components imports there(that's what breaks the HMR) to your `.stories.tsx` file
you can add the following to `preview.js` but it's worse than full reload as HMR won't take any effect to `reactRunner.scope`
```js
if (module && module.hot && module.hot.accept) {
  module.hot.accept();
}
```

**Comment by nihgwu** [comment]
I added a note about HMR in README via https://github.com/nihgwu/storybook-addon-react-runner/commit/7c71e9efe258c3f0270803da0dd58c4ea72052da
